import type { ConfiguracionPrecios } from "../types";

export const PRECIOS_POR_DEFECTO: ConfiguracionPrecios = {
  costeFan: 7.5,
  ventaFan: 15,
  costeRetroPlayer: 11,
  ventaRetroPlayer: 18,
  costePlayer: 11,
  ventaPlayer: 18,
  costeRetro: 12,
  ventaRetro: 18,
  costeTrajeInfantil: 9.3,
  ventaTrajeInfantil: 18,
  costeParche: 0.9,
  ventaParche: 0.9,
  costeTalla3XL: 0.9,
  ventaTalla3XL: 0,
  costeTalla4XL: 1.7,
  ventaTalla4XL: 0,
  costePersonalizacion: 0.9,
  ventaPersonalizacion: 2,
  costeMangaLarga: 5.2,
  ventaMangaLarga: 2,
  costeFijoPedido: 4,
};
