import type { ConfiguracionPrecios } from "../types";

export const PRECIOS_POR_DEFECTO: ConfiguracionPrecios = {
  costeFan: 6.5,
  ventaFan: 15,
  costePlayer: 9.4,
  ventaPlayer: 18,
  costeRetro: 9.4,
  ventaRetro: 18,
  costePersonalizada: 8.5,
  ventaPersonalizada: 17,
  costeInfantil: 6.5,
  ventaInfantil: 15,
  costeParche: 0.5,
  ventaParche: 2,
  costeTalla3XL: 0.9,
  ventaTalla3XL: 0,
  costeTalla4XL: 1.7,
  ventaTalla4XL: 0,
  costePersonalizacion: 2,
  ventaPersonalizacion: 2,
  costeMangaLarga: 2,
  ventaMangaLarga: 2,
  costeFijoPedido: 4,
};
