"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { cargarCatalogo, eliminarVariante, guardarProducto, guardarVariante, subirImagen, type CatalogoProducto, type CatalogoVariante } from "../../lib/catalogo";

const tipos=["Fan","Player","Retro","Infantil","Manga larga"];
const ediciones=["LaLiga","Champions","Copa","Retro"];
const emptyVar=():CatalogoVariante=>({id:"",producto_id:"",edicion:"LaLiga",tipo:"Fan",etiqueta:"",precio:null,imagen_url:null});
export default function CatalogoPage(){
 const [items,setItems]=useState<CatalogoProducto[]>([]); const [selected,setSelected]=useState<CatalogoProducto|null>(null); const [name,setName]=useState(""); const [desc,setDesc]=useState(""); const [active,setActive]=useState(true); const [variant,setVariant]=useState(emptyVar()); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const inputRef=useRef<HTMLInputElement>(null);
 async function load(){try{setItems(await cargarCatalogo())}catch(e){setMessage(e instanceof Error?e.message:"No se pudo cargar el catálogo")}}
 useEffect(()=>{load()},[]);
 function choose(p:CatalogoProducto){setSelected(p);setName(p.nombre);setDesc(p.descripcion);setActive(p.activo);setVariant(emptyVar())}
 function newProduct(){setSelected(null);setName("");setDesc("");setActive(true);setVariant(emptyVar())}
 async function image(file?:File){if(!file||!file.type.startsWith("image/"))return;setBusy(true);try{const url=await subirImagen(file);setVariant(v=>({...v,imagen_url:url}));setMessage("Imagen lista")}catch(e){setMessage(e instanceof Error?e.message:"No se pudo subir la imagen")}finally{setBusy(false)}}
 async function save(){if(!name.trim()){setMessage("Escribe un nombre");return}setBusy(true);try{const p=await guardarProducto({id:selected?.id,nombre:name.trim(),descripcion:desc,activo:active});if(variant.etiqueta||variant.imagen_url){await guardarVariante({...variant,producto_id:p.id,id:variant.id||undefined})}setMessage("Guardado");await load();const fresh=(await cargarCatalogo()).find(x=>x.id===p.id);if(fresh)choose(fresh)}catch(e){setMessage(e instanceof Error?e.message:"No se pudo guardar")}finally{setBusy(false)}}
 async function saveVar(v:CatalogoVariante){setBusy(true);try{await guardarVariante({...v,producto_id:selected!.id,id:v.id||undefined});await load();const fresh=(await cargarCatalogo()).find(x=>x.id===selected!.id);if(fresh)choose(fresh)}finally{setBusy(false)}}
 return <main className="min-h-screen bg-background p-6 text-foreground"><div className="mx-auto max-w-7xl space-y-6">
  <header className="flex items-center justify-between"><div><Link href="/" className="text-sm text-muted">← Volver a pedidos</Link><h1 className="mt-2 text-3xl font-bold">Catálogo de productos</h1><p className="text-muted">Añade productos, versiones y sus imágenes.</p></div><button onClick={newProduct} className="rounded-xl bg-black px-4 py-2 text-white">Nuevo producto</button></header>
  {message&&<p className="rounded-xl bg-surface p-3 text-sm">{message}</p>}
  <div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="space-y-2">{items.map(p=><button key={p.id} onClick={()=>choose(p)} className={`block w-full rounded-xl p-4 text-left ${selected?.id===p.id?"bg-black text-white":"bg-surface"}`}><b>{p.nombre}</b><span className="block text-xs opacity-70">{p.variantes?.length??0} variantes</span></button>)}{!items.length&&<div className="rounded-xl border border-dashed p-5 text-sm text-muted">Aún no hay productos.</div>}</aside>
  <section className="space-y-5 rounded-2xl bg-surface p-5"><div className="grid gap-4 md:grid-cols-2"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3" placeholder="Camiseta Betis"/></label><label>Descripción<textarea value={desc} onChange={e=>setDesc(e.target.value)} className="mt-2 w-full rounded-xl border bg-background p-3" rows={3}/></label></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Disponible en catálogo</label>
  <div className="rounded-xl border border-dashed p-4" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();image(e.dataTransfer.files[0])}} onPaste={e=>{const f=e.clipboardData.files[0];if(f)image(f)}}><div className="flex items-center justify-between"><div><b>Imagen de la variante</b><p className="text-sm text-muted">Arrastra una imagen aquí o pégala con Ctrl/Cmd+V.</p></div><button type="button" onClick={()=>inputRef.current?.click()} className="rounded-lg bg-surface-subtle px-3 py-2 text-sm">Elegir archivo</button><input ref={inputRef} hidden type="file" accept="image/*" onChange={e=>image(e.target.files?.[0])}/></div>{variant.imagen_url&&<img src={variant.imagen_url} alt="" className="mt-4 h-28 w-28 rounded-xl object-cover"/>}</div>
  <div className="grid gap-3 md:grid-cols-4"><select value={variant.edicion} onChange={e=>setVariant(v=>({...v,edicion:e.target.value}))} className="rounded-xl border bg-background p-3">{ediciones.map(x=><option key={x}>{x}</option>)}</select><select value={variant.tipo} onChange={e=>setVariant(v=>({...v,tipo:e.target.value}))} className="rounded-xl border bg-background p-3">{tipos.map(x=><option key={x}>{x}</option>)}</select><input value={variant.etiqueta} onChange={e=>setVariant(v=>({...v,etiqueta:e.target.value}))} placeholder="Etiqueta (ej. 24/25)" className="rounded-xl border bg-background p-3"/><input type="number" value={variant.precio??""} onChange={e=>setVariant(v=>({...v,precio:e.target.value?Number(e.target.value):null}))} placeholder="Precio" className="rounded-xl border bg-background p-3"/></div>
  <button disabled={busy} onClick={save} className="rounded-xl bg-black px-5 py-3 font-medium text-white disabled:opacity-50">{selected?"Guardar cambios":"Crear producto"}</button>
  {selected&&<div className="space-y-3"><h2 className="font-bold">Versiones guardadas</h2>{(selected.variantes||[]).map(v=><div key={v.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-3"><span className="font-medium">{v.edicion} · {v.tipo}</span><span className="text-sm text-muted">{v.etiqueta||"Sin etiqueta"}</span>{v.imagen_url&&<img src={v.imagen_url} alt="" className="h-12 w-12 rounded object-cover"/>}<button className="ml-auto text-sm underline" onClick={()=>setVariant(v)}>Editar</button><button className="text-sm text-red-600" onClick={async()=>{await eliminarVariante(v.id);load()}}>Eliminar</button></div>)}<button onClick={()=>setVariant(emptyVar())} className="rounded-xl bg-surface-subtle px-4 py-2 text-sm">Añadir otra versión</button></div>}
  </section></div></div></main>
}