import { StyleSheet } from "react-native";
import { colors, helpers, radius, shadows, spacing, typography } from "@/theme";

export const styles = StyleSheet.create({
  screen: { ...helpers.screen, padding: spacing.lg },
  scrollScreen: { ...helpers.screen },
  scrollContent: { ...helpers.screenContent },
  card: { ...helpers.card, ...shadows.card, marginBottom: spacing.md },
  elevatedCard: { ...helpers.cardElevated, ...shadows.card, marginBottom: spacing.lg },
  title: { ...typography.title, marginBottom: spacing.md },
  subtitle: { ...typography.h2, marginBottom: spacing.sm },
  eyebrow: { ...typography.eyebrow, marginBottom: spacing.xs },
  text: { ...typography.body, marginBottom: spacing.xs },
  muted: { ...typography.muted },
  label: { ...typography.label, marginBottom: spacing.sm, marginTop: spacing.sm },
  input: { ...helpers.input, marginBottom: spacing.md },
  row: { flexDirection: "row", gap: spacing.sm, flexWrap: "wrap", alignItems: "center" },
  between: { flexDirection: "row", justifyContent: "space-between", gap: spacing.md, alignItems: "center" },
  button: { ...helpers.primaryButton, marginVertical: spacing.xs },
  secondaryButton: { ...helpers.secondaryButton, marginVertical: spacing.xs },
  dangerButton: { ...helpers.dangerButton, marginVertical: spacing.xs },
  buttonText: { color: colors.black, fontWeight: "900", letterSpacing: 0.2 },
  secondaryText: { color: colors.text, fontWeight: "800" },
  dangerText: { color: colors.danger, fontWeight: "900" },
  badge: { backgroundColor: "rgba(182,255,0,0.12)", color: colors.neon, borderColor: colors.neonDark, borderWidth: 1, paddingVertical: 4, paddingHorizontal: 10, borderRadius: radius.pill, overflow: "hidden", fontWeight: "900", fontSize: 12, textTransform: "uppercase" },
  badgeMuted: { backgroundColor: colors.surfaceElevated, color: colors.textMuted, borderColor: colors.borderStrong, borderWidth: 1, paddingVertical: 4, paddingHorizontal: 10, borderRadius: radius.pill, overflow: "hidden", fontWeight: "800", fontSize: 12 },
  error: { color: colors.danger, marginBottom: spacing.md, fontWeight: "800" },
  success: { color: colors.success, fontWeight: "900" },
  warning: { color: colors.warning, fontWeight: "900" },
  blue: { color: colors.blue, fontWeight: "900" },
  statGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md },
  stat: { flexGrow: 1, flexBasis: "47%", backgroundColor: colors.surfaceElevated, borderColor: colors.border, borderWidth: 1, borderRadius: radius.md, padding: spacing.md },
  statLabel: { ...typography.label },
  statValue: { color: colors.text, fontSize: 20, fontWeight: "900", marginTop: spacing.xs },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: spacing.md },
  accentBar: { position: "absolute", left: 0, top: 14, bottom: 14, width: 3, borderRadius: 3, backgroundColor: colors.neon },
});
