create table if not exists hostinger_mail_message_statuses (
  id bigint generated by default as identity primary key,
  message_id text not null,
  mailbox text not null,
  status text not null default 'pendiente' check (status in ('pendiente', 'en_proceso', 'respondido')),
  internal_tags text[] not null default '{}',
  internal_notes text not null default '',
  related_pedido_id bigint references pedidos(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (message_id, mailbox)
);

alter table hostinger_mail_message_statuses enable row level security;
