alter table public.configuracion_precios
  add column if not exists coste_player numeric,
  add column if not exists venta_player numeric,
  add column if not exists coste_retro numeric,
  add column if not exists venta_retro numeric,
  add column if not exists coste_traje_infantil numeric,
  add column if not exists venta_traje_infantil numeric,
  add column if not exists coste_parche numeric,
  add column if not exists venta_parche numeric,
  add column if not exists coste_talla_3xl numeric,
  add column if not exists venta_talla_3xl numeric,
  add column if not exists coste_talla_4xl numeric,
  add column if not exists venta_talla_4xl numeric;

insert into public.configuracion_precios (
  id,
  coste_fan,
  venta_fan,
  coste_retro_player,
  venta_retro_player,
  coste_player,
  venta_player,
  coste_retro,
  venta_retro,
  coste_traje_infantil,
  venta_traje_infantil,
  coste_parche,
  venta_parche,
  coste_talla_3xl,
  venta_talla_3xl,
  coste_talla_4xl,
  venta_talla_4xl,
  coste_personalizacion,
  venta_personalizacion,
  coste_manga_larga,
  venta_manga_larga,
  coste_fijo_pedido,
  updated_at
)
values (
  1,
  7.5,
  15,
  11,
  18,
  11,
  18,
  12,
  18,
  9.3,
  18,
  0.9,
  0.9,
  0.9,
  0,
  1.7,
  0,
  0.9,
  2,
  5.2,
  2,
  4,
  now()
)
on conflict (id) do update set
  coste_fan = excluded.coste_fan,
  coste_retro_player = excluded.coste_retro_player,
  coste_player = excluded.coste_player,
  coste_retro = excluded.coste_retro,
  coste_traje_infantil = excluded.coste_traje_infantil,
  coste_parche = excluded.coste_parche,
  coste_talla_3xl = excluded.coste_talla_3xl,
  coste_talla_4xl = excluded.coste_talla_4xl,
  coste_personalizacion = excluded.coste_personalizacion,
  coste_manga_larga = excluded.coste_manga_larga,
  updated_at = excluded.updated_at;
