alter table pedidos
add column if not exists numero_seguimiento text default null,
add column if not exists transportista_codigo text default null,
add column if not exists transportista_nombre text default null,
add column if not exists tracking_estado text default null,
add column if not exists tracking_subestado text default null,
add column if not exists tracking_estado_interno text default null,
add column if not exists tracking_ultimo_evento text default null,
add column if not exists tracking_ultima_ubicacion text default null,
add column if not exists tracking_actualizado_at timestamp with time zone default null,
add column if not exists tracking_registrado_at timestamp with time zone default null,
add column if not exists tracking_error text default null,
add column if not exists tracking_datos jsonb default null;

create table if not exists push_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  expo_push_token text not null,
  platform text not null default 'android',
  device_name text default null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  unique(user_id, expo_push_token)
);

create table if not exists tracking_events (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  estado_anterior text default null,
  estado_nuevo text default null,
  subestado_anterior text default null,
  subestado_nuevo text default null,
  estado_interno_anterior text default null,
  estado_interno_nuevo text default null,
  evento text default null,
  ubicacion text default null,
  raw jsonb default null,
  notified boolean not null default false,
  created_at timestamp with time zone default now()
);

create index if not exists pedidos_numero_seguimiento_idx on pedidos(numero_seguimiento) where numero_seguimiento is not null;
create index if not exists tracking_events_pedido_id_created_at_idx on tracking_events(pedido_id, created_at desc);
create index if not exists push_tokens_user_id_idx on push_tokens(user_id);

-- RLS sugerida si se activa: push_tokens debe permitir select/insert/update/delete solo donde auth.uid() = user_id.
-- tracking_events debería ser legible para usuarios autorizados a leer el pedido asociado; las escrituras quedan para backend con service role.
